import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Worker = { id: string; label: string; username: string; status: string; buyerId: string | null };
type Buyer = { id: string; name: string; planBroadcast: boolean; planComment: boolean; broadcastActive: boolean; commentActive: boolean; commentAccountConnected: boolean; workerId: string | null };
type Package = { packageId?: string; id?: string; service: "BROADCAST" | "COMMENT"; name: string; price: number; durationDays: number; maxGroups: number; enabled?: boolean };
type Dashboard = { onboarding?: boolean; buyer: Buyer | null; worker: Worker | null; broadcast: { wording: string; groups: string[]; intervalMinutes: number; maxGroups?: number } | null; comment: { bases: string[]; division: string; keywords: string[]; blacklist: string[]; wording: string; mode: "APPROVAL" | "AUTO" } | null; activity: { kind: string; status: string; label: string; at: string }[] };
declare global { interface Window { Telegram?: { WebApp?: { initData: string; ready: () => void; expand: () => void } } } }
const telegramApp = window.Telegram?.WebApp;
telegramApp?.ready(); telegramApp?.expand();
const buyerHeaders = { ...(telegramApp?.initData ? { "x-telegram-init-data": telegramApp.initData } : { "x-buyer-id": "0" }), "content-type": "application/json" };
const api = async <T,>(url: string, options?: RequestInit): Promise<T> => { const headers = new Headers(options?.headers); if (telegramApp?.initData) headers.set("x-telegram-init-data", telegramApp.initData); else if (!headers.has("x-buyer-id")) headers.set("x-buyer-id", "0"); const res = await fetch(url, { ...options, headers }); const data = await res.json(); if (!res.ok) throw new Error(data.reason ?? data.error); return data; };

function Toggle({ on, disabled, onClick }: { on: boolean; disabled?: boolean; onClick: () => void }) { return <button className={`toggle ${on ? "on" : ""}`} disabled={disabled} onClick={onClick}><i /></button>; }
function Tag({ children, kind = "soft" }: { children: ReactNode; kind?: string }) { return <span className={`tag ${kind}`}>{children}</span>; }

type ProductIconName = "broadcast" | "comment";

function ProductIcon({ name }: { name: ProductIconName }) {
  const common = { fill: "none", stroke: "currentColor", strokeWidth: 1.7, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
  return name === "broadcast"
    ? <svg viewBox="0 0 24 24" aria-hidden="true"><path {...common} d="m5 10.2 11.6-5.1v13.8L5 13.8v-3.6Z" /><path {...common} d="M8.3 15.2 9.6 19h3.1l-.8-4.9M19 8.2c1 .8 1.5 1.9 1.5 3.1s-.5 2.3-1.5 3.1" /></svg>
    : <svg viewBox="0 0 24 24" aria-hidden="true"><path {...common} d="M4.5 6.7c0-1.2 1-2.2 2.2-2.2h10.6c1.2 0 2.2 1 2.2 2.2v6.6c0 1.2-1 2.2-2.2 2.2h-6.4L7 19v-3.5H6.7c-1.2 0-2.2-1-2.2-2.2V6.7Z" /><path {...common} d="M8 10h.01M12 10h.01M16 10h.01" strokeWidth="2.5" /></svg>;
}

function activityLabel(kind: string) { return kind === "broadcast" ? "Sebar" : "Komen"; }

function WelcomeApp() {
  const [chosen, setChosen] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [packages, setPackages] = useState<Package[] | null>(null);
  useEffect(() => { void api<Package[]>("/api/public/packages").then(setPackages).catch((e) => setError((e as Error).message)); }, []);
  const choose = async (packageId: string) => {
    setBusy(true); setError("");
    try { await api("/api/public/checkout", { method: "POST", headers: buyerHeaders, body: JSON.stringify({ packageId }) }); setChosen(packageId); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  if (!packages) return <main className="shell loading">Memuat paket…</main>;
  const groups = [{ service: "BROADCAST" as const, title: "Auto Sebar", copy: "Pilih cara sebar promosi yang paling pas untuk lo." }, { service: "COMMENT" as const, title: "Auto Komen MF", copy: "Pilih paket untuk menangkap peluang dari base pilihan lo." }];
  return <main className="shell welcome">
    <header><div className="eyebrow">PUSAT PROMOSI</div><h1>Pilih paket yang pas buat lo.</h1><p>Setiap layanan punya beberapa pilihan paket. Pilih satu, lalu lanjutkan pembayaran dari sini.</p></header>
    {error && <div className="notice error">{error}</div>}
    {groups.map((group) => { const items = packages.filter((item) => item.service === group.service); return <section className="catalog-group" key={group.service}><div className="catalog-heading"><span className={"icon-tile " + (group.service === "BROADCAST" ? "broadcast-icon" : "comment-icon")}><ProductIcon name={group.service === "BROADCAST" ? "broadcast" : "comment"} /></span><div><div className="label">{group.title.toUpperCase()}</div><h2>{group.copy}</h2></div></div>{items.length ? <div className="catalog-list">{items.map((item) => { const packageId = item.packageId ?? item.id ?? ""; return <article className="catalog-item" key={packageId}><div><b>{item.name}</b><span>{item.durationDays} hari akses{group.service === "BROADCAST" ? ` · hingga ${item.maxGroups} grup LPM` : ""}</span></div><strong>Rp{new Intl.NumberFormat("id-ID").format(item.price)}</strong><button className={group.service === "COMMENT" ? "catalog-buy orange-action" : "catalog-buy"} disabled={busy || chosen === packageId} onClick={() => void choose(packageId)}>{chosen === packageId ? "Lanjutkan pembayaran" : "Pilih paket"}</button></article>; })}</div> : <div className="empty">Belum ada paket yang dibuka untuk layanan ini.</div>}</section>; })}
  </main>;
}

function BuyerApp() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = async () => { try { setData(await api<Dashboard>("/api/buyer/dashboard", { headers: buyerHeaders })); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, []);
  const change = async (feature: "BROADCAST" | "COMMENT", active: boolean) => { setBusy(feature); setError(""); try { await api("/api/buyer/toggle", { method: "POST", headers: buyerHeaders, body: JSON.stringify({ feature, active }) }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(""); } };
  const connect = async () => { setBusy("CONNECT"); try { await api("/api/buyer/connect-comment-account", { method: "POST", headers: buyerHeaders }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(""); } };
  if (!data) return <main className="shell loading">{error ? <div className="notice error">{error}</div> : "Memuat layanan…"}</main>;
  if (!data.buyer) return <WelcomeApp />;
  const { buyer, worker, broadcast, comment } = data;
  return <main className="shell">
    <header><div className="eyebrow">PUSAT PROMOSI</div><h1>Halo, {buyer.name}.</h1><p>Layanan lo sudah disiapkan. Tinggal pantau dan nyalakan saat diperlukan.</p></header>
    {error && <div className="notice error">{error}</div>}
    <section className="service-card broadcast-card"><div className="service-top"><div><span className="icon-tile broadcast-icon"><ProductIcon name="broadcast" /></span><div><div className="label">AUTO SEBAR</div><h2>{buyer.planBroadcast ? "Siap untuk promosi" : "Belum ada akses"}</h2></div></div><Toggle on={buyer.broadcastActive} disabled={busy === "BROADCAST" || !buyer.planBroadcast} onClick={() => void change("BROADCAST", !buyer.broadcastActive)} /></div>
      {buyer.planBroadcast && broadcast ? <><div className="signal"><b>{buyer.broadcastActive ? "Sedang berjalan" : "Dijeda"}</b><span>{worker ? `@${worker.username}` : "Akun kerja belum dipilih"} · {broadcast.groups.length}/{broadcast.maxGroups ?? 15} grup · jeda {broadcast.intervalMinutes}m</span></div><div className="excerpt">{broadcast.wording}</div><div className="group-pills">{broadcast.groups.slice(0, 4).map((group) => <Tag key={group}>@{group}</Tag>)}{broadcast.groups.length > 4 && <Tag>+{broadcast.groups.length - 4}</Tag>}</div></> : <p className="card-copy">Admin akan menyiapkan akun kerja, wording, dan grup tujuan lo.</p>}
    </section>
    <section className="service-card comment-card"><div className="service-top"><div><span className="icon-tile comment-icon"><ProductIcon name="comment" /></span><div><div className="label">AUTO KOMEN MF</div><h2>{buyer.planComment ? "Pencarian buyer" : "Belum ada akses"}</h2></div></div><Toggle on={buyer.commentActive} disabled={busy === "COMMENT" || !buyer.planComment} onClick={() => void change("COMMENT", !buyer.commentActive)} /></div>
      {buyer.planComment && <>{!buyer.commentAccountConnected ? <button className="outline" disabled={busy === "CONNECT"} onClick={() => void connect()}>{busy === "CONNECT" ? "Menyambungkan…" : "Hubungkan akun Telegram"}</button> : <div className="signal"><b>{buyer.commentActive ? "Sedang memantau" : "Dijeda"}</b><span>{comment ? `${comment.division} · ${comment.mode === "AUTO" ? "Otomatis" : "By approval"}` : "Admin sedang melengkapi setup"}</span></div>}{comment && <div className="compact-grid"><div><span>BASE</span><b>{comment.bases.length} tujuan</b></div><div><span>KEYWORD</span><b>{comment.keywords.length} aktif</b></div><div><span>MODE</span><b>{comment.mode === "AUTO" ? "Otomatis" : "Approval"}</b></div></div>}</>}
    </section>
    <section className="activity"><div className="section-title"><span>AKTIVITAS TERBARU</span><b>30 hari</b></div>{data.activity.length ? data.activity.map((item, index) => <div className="activity-row" key={index}><i className={item.kind.toLowerCase()} /><div><b>{item.label}</b><span>{item.kind} · {new Date(item.at).toLocaleString("id-ID")}</span></div><Tag>{item.status}</Tag></div>) : <div className="empty">Belum ada aktivitas. Admin akan menyelesaikan setup dulu.</div>}</section>
  </main>;
}

function AdminApp() {
  const [overview, setOverview] = useState<{ buyers: Buyer[]; workers: Worker[]; broadcasts: { buyerId: string; wording: string; groups: string[]; intervalMinutes: number }[]; comments: { buyerId: string; bases: string[]; division: string; keywords: string[]; blacklist: string[]; wording: string; mode: "APPROVAL" | "AUTO" }[]; packages: Package[] } | null>(null);
  const [panelOpen, setPanelOpen] = useState(false); const [settingUp, setSettingUp] = useState(false); const [catalogOpen, setCatalogOpen] = useState(false); const [selected, setSelected] = useState("buyer-demo"); const [message, setMessage] = useState(""); const [editingPackage, setEditingPackage] = useState<Package | null>(null);
  const [form, setForm] = useState({ workerId: "", wording: "", groups: "", intervalMinutes: "15", bases: "", division: "", keywords: "", blacklist: "", commentWording: "", mode: "APPROVAL", planBroadcast: true, planComment: true });
  const load = async () => { try { setOverview(await api("/api/admin/overview")); } catch (e) { setMessage((e as Error).message); } };
  useEffect(() => { void load(); }, []);
  const buyer = overview?.buyers.find((item) => item.id === selected); const assigned = overview?.broadcasts.find((item) => item.buyerId === selected); const comment = overview?.comments.find((item) => item.buyerId === selected);
  useEffect(() => { if (!buyer) return; setForm({ workerId: buyer.workerId ?? "", wording: assigned?.wording ?? "", groups: assigned?.groups.join("\n") ?? "", intervalMinutes: String(assigned?.intervalMinutes ?? 15), bases: comment?.bases.join("\n") ?? "", division: comment?.division ?? "Produk", keywords: comment?.keywords.join("\n") ?? "", blacklist: comment?.blacklist.join("\n") ?? "", commentWording: comment?.wording ?? "", mode: comment?.mode ?? "APPROVAL", planBroadcast: buyer.planBroadcast, planComment: buyer.planComment }); }, [selected, buyer?.workerId, assigned?.wording, comment?.division]);
  const update = (key: keyof typeof form, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  const addBuyer = async () => { const name = prompt("Nama pelanggan"); const telegramId = prompt("ID Telegram pelanggan"); if (!name || !telegramId) return; try { const result = await api<{ buyer: Buyer }>("/api/admin/buyers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, telegramId }) }); setSelected(result.buyer.id); setSettingUp(true); await load(); } catch (e) { setMessage((e as Error).message); } };
  const addWorker = async () => { const label = prompt("Nama akun kerja"); const username = prompt("Username akun tanpa @"); if (!label || !username) return; try { await api("/api/admin/workers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ label, username }) }); await load(); } catch (e) { setMessage((e as Error).message); } };
  const submit = async () => { if (!buyer) return; setMessage(""); try { await api("/api/admin/buyers/" + selected + "/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, groups: form.groups.split("\n").filter(Boolean) }) }); setMessage("Layanan pelanggan sudah diperbarui."); await load(); } catch (e) { setMessage((e as Error).message); } };
  const startPackage = (service: Package["service"]) => setEditingPackage({ service, name: "", price: 0, durationDays: 30, maxGroups: 15, enabled: false });
  const updateEditingPackage = (key: "name" | "price" | "durationDays" | "maxGroups" | "enabled", value: string | boolean) => setEditingPackage((item) => item ? { ...item, [key]: key === "enabled" ? Boolean(value) : key === "name" ? String(value) : Number(value) } : item);
  const savePackage = async () => { if (!editingPackage) return; setMessage(""); try { const isExisting = Boolean(editingPackage.id); await api(isExisting ? "/api/admin/packages/" + editingPackage.id : "/api/admin/packages", { method: isExisting ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(editingPackage) }); setEditingPackage(null); setMessage("Paket langganan sudah disimpan."); await load(); } catch (e) { setMessage((e as Error).message); } };
  const removePackage = async (item: Package) => { if (!item.id || !window.confirm(`Hapus paket ${item.name}?`)) return; setMessage(""); try { await api("/api/admin/packages/" + item.id, { method: "DELETE" }); setMessage("Paket sudah dihapus."); await load(); } catch (e) { setMessage((e as Error).message); } };
  if (!overview) return <main className="shell loading">Membuka layanan…</main>;
  const activeCount = overview.buyers.filter((item) => item.planBroadcast || item.planComment).length;
  const readyWorkers = overview.workers.filter((item) => item.status === "AVAILABLE").length;
  return <main className="shell admin">
    <header><div className="eyebrow">PUSAT PROMOSI</div><h1>Halo, Admin.</h1><p>Pantau layanan dan permintaan dari satu tempat.</p></header>
    {message && <div className="notice">{message}</div>}
    {!panelOpen ? <><section className="service-card broadcast-card"><div className="service-top"><div><span className="icon-tile broadcast-icon"><ProductIcon name="broadcast" /></span><div><div className="label">PELANGGAN</div><h2>{activeCount} layanan berjalan</h2></div></div><Tag>{overview.buyers.length} total</Tag></div><div className="signal"><b>{readyWorkers} akun promosi siap dipakai</b><span>Setiap pelanggan yang aktif dikelola dari satu tempat.</span></div></section>
      <section className="service-card comment-card"><div className="service-top"><div><span className="icon-tile comment-icon"><ProductIcon name="comment" /></span><div><div className="label">AKUN PROMOSI</div><h2>{readyWorkers + " akun siap dipakai"}</h2></div></div><Tag>{overview.workers.length} total</Tag></div><div className="signal"><b>Akun promosi akan dialokasikan setelah pembayaran Auto Sebar tervalidasi.</b><span>Jumlah akun menentukan slot yang bisa dijual.</span></div></section>
      <button className="panel-trigger" onClick={() => setPanelOpen(true)}><span>Panel Admin</span><small>Kelola pelanggan dan akun promosi</small></button></> :
      <section className="admin-panel"><div className="panel-title"><div><div className="eyebrow">PANEL ADMIN</div><h2>Kelola layanan.</h2></div><button className="close-panel" onClick={() => { setPanelOpen(false); setSettingUp(false); }}>Tutup</button></div>
        <div className="admin-snapshot"><div><span>PELANGGAN</span><b>{overview.buyers.length}</b></div><div><span>AKUN SIAP</span><b>{readyWorkers}</b></div><div><span>LAYANAN AKTIF</span><b>{activeCount}</b></div></div>
        <button className="admin-tool" onClick={() => { setCatalogOpen(!catalogOpen); setEditingPackage(null); }}><span className="icon-tile comment-icon"><ProductIcon name="comment" /></span><div><b>Atur paket langganan</b><span>Buat pilihan paket Auto Sebar dan Auto Komen untuk buyer.</span></div><i>{catalogOpen ? "−" : "+"}</i></button>
        {catalogOpen && <section className="package-manager"><div className="package-manager-head"><div><div className="label">PAKET LANGGANAN</div><h3>Pilihan paket buyer</h3><p>Atur nama, harga, masa aktif, dan batas grup untuk Auto Sebar.</p></div><Tag>{overview.packages.length} paket</Tag></div>
          {editingPackage && <section className="package-editor"><div className="section-title"><span>{editingPackage.id ? "UBAH PAKET" : "PAKET BARU"}</span><button className="quiet-button" onClick={() => setEditingPackage(null)}>Batal</button></div><div className="editor-grid"><label>Nama paket<input value={editingPackage.name} maxLength={40} onChange={(e) => updateEditingPackage("name", e.target.value)} placeholder={editingPackage.service === "BROADCAST" ? "Contoh: Sebar Mulai" : "Contoh: Komen Mulai"} /></label><label>Harga paket<input type="number" min="0" max="10000000" value={editingPackage.price} onChange={(e) => updateEditingPackage("price", e.target.value)} placeholder="Contoh: 25000" /></label><label>Masa aktif (hari)<input type="number" min="1" max="365" value={editingPackage.durationDays} onChange={(e) => updateEditingPackage("durationDays", e.target.value)} /></label>{editingPackage.service === "BROADCAST" && <label>Maksimal grup LPM<input type="number" min="1" max="15" value={editingPackage.maxGroups} onChange={(e) => updateEditingPackage("maxGroups", e.target.value)} /></label>}</div><label className="package-switch"><input type="checkbox" checked={Boolean(editingPackage.enabled)} onChange={(e) => updateEditingPackage("enabled", e.target.checked)} /> Tampilkan paket ini ke buyer</label><button className="save" onClick={() => void savePackage()}>Simpan paket</button></section>}
          {(["BROADCAST", "COMMENT"] as const).map((service) => { const items = overview.packages.filter((item) => item.service === service); const isBroadcast = service === "BROADCAST"; return <section className="package-service" key={service}><div className="package-service-head"><div><span>{isBroadcast ? "AUTO SEBAR" : "AUTO KOMEN MF"}</span><b>{isBroadcast ? "Paket sebar promosi" : "Paket pencarian buyer"}</b></div><button onClick={() => startPackage(service)}>+ Tambah paket</button></div>{items.length ? <div className="package-rows">{items.map((item) => <article className="package-row" key={item.id}><div><b>{item.name}</b><span>Rp{new Intl.NumberFormat("id-ID").format(item.price)} · {item.durationDays} hari{isBroadcast ? ` · maks. ${item.maxGroups} LPM` : ""}</span></div><div className="package-row-actions"><Tag>{item.enabled ? "Tampil" : "Disimpan"}</Tag><button onClick={() => setEditingPackage({ ...item })}>Ubah</button><button className="danger-button" onClick={() => void removePackage(item)}>Hapus</button></div></article>)}</div> : <div className="package-empty">Belum ada paket. Tambahkan pilihan pertama untuk layanan ini.</div>}</section>; })}
        </section>}
        <button className="admin-tool" onClick={() => setSettingUp(!settingUp)}><span className="icon-tile broadcast-icon"><ProductIcon name="broadcast" /></span><div><b>Atur layanan pelanggan</b><span>Tambahkan pelanggan, lalu siapkan layanan yang dia ambil.</span></div><i>{settingUp ? "−" : "+"}</i></button>
        <button className="admin-tool" onClick={() => void addWorker()}><span className="icon-tile comment-icon"><ProductIcon name="comment" /></span><div><b>Tambah akun promosi</b><span>Akun baru akan tersedia untuk pelanggan berikutnya.</span></div><i>+</i></button>
        {settingUp && <section className="setup embedded-setup"><div className="section-title"><span>LAYANAN PELANGGAN</span><button onClick={() => void addBuyer()}>+ tambah pelanggan</button></div><div className="buyer-picker">{overview.buyers.map((item) => <button className={selected === item.id ? "chosen" : ""} key={item.id} onClick={() => setSelected(item.id)}><b>{item.name}</b><span>{item.planBroadcast || item.planComment ? "siap" : "belum diatur"}</span></button>)}</div>{buyer ? <><div className="access-pills"><label><input type="checkbox" checked={form.planBroadcast} onChange={(e) => update("planBroadcast", e.target.checked)} /> Auto Sebar</label><label><input type="checkbox" checked={form.planComment} onChange={(e) => update("planComment", e.target.checked)} /> Auto Komen</label></div>{form.planBroadcast && <fieldset><legend>Auto Sebar · akun khusus</legend><label>Akun kerja<select value={form.workerId} onChange={(e) => update("workerId", e.target.value)}><option value="">Pilih akun</option>{overview.workers.filter((item) => !item.buyerId || item.buyerId === selected).map((item) => <option key={item.id} value={item.id}>{item.label} · @{item.username}</option>)}</select></label><label>Wording<textarea value={form.wording} onChange={(e) => update("wording", e.target.value)} placeholder="Wording promosi pelanggan…" /></label><label>Grup tujuan, satu per baris<textarea value={form.groups} onChange={(e) => update("groups", e.target.value)} placeholder="@grup_satu\n@grup_dua" /></label><label>Jeda kirim (menit)<input value={form.intervalMinutes} inputMode="numeric" onChange={(e) => update("intervalMinutes", e.target.value)} /></label></fieldset>}{form.planComment && <fieldset><legend>Auto Komen · akun pelanggan</legend><label>Base tujuan<textarea value={form.bases} onChange={(e) => update("bases", e.target.value)} placeholder="@base_satu\n@base_dua" /></label><label>Divisi<input value={form.division} onChange={(e) => update("division", e.target.value)} /></label><label>Keyword yang dicari<textarea value={form.keywords} onChange={(e) => update("keywords", e.target.value)} /></label><label>Blacklist keyword OOT<textarea value={form.blacklist} onChange={(e) => update("blacklist", e.target.value)} /></label><label>Wording komentar<textarea value={form.commentWording} onChange={(e) => update("commentWording", e.target.value)} /></label><label>Metode<select value={form.mode} onChange={(e) => update("mode", e.target.value)}><option value="APPROVAL">By approval</option><option value="AUTO">Otomatis</option></select></label></fieldset>}<button className="save" onClick={() => void submit()}>Simpan layanan pelanggan</button></> : <div className="empty">Tambahkan pelanggan dulu untuk menyiapkan layanannya.</div>}</section>}
      </section>}
  </main>;
}

function App() {
  const [role, setRole] = useState<"ADMIN" | "BUYER" | null>(null); const [error, setError] = useState("");
  useEffect(() => { void api<{ role: "ADMIN" | "BUYER" }>("/api/app/session").then((session) => setRole(session.role)).catch((e) => setError((e as Error).message)); }, []);
  if (error) return <main className="shell loading"><div className="notice error">{error}</div></main>;
  if (!role) return <main className="shell loading">Membuka layanan…</main>;
  return role === "ADMIN" ? <AdminApp /> : <BuyerApp />;
}

createRoot(document.getElementById("root")!).render(<App />);
